FROM node:18-alpine3.15

COPY Pipfile* /worker/
ENV PYTHONPATH="/worker"
WORKDIR /worker
RUN pip install pipenv
RUN pipenv requirements > requirements.txt
RUN pipenv requirements --dev > requirements-dev.txt


RUN apt-get update -yqq && apt-get install -yqq curl cmake g++ build-essential
# Adding libspatialindex for geopandas or other spatial librairies
RUN curl -L https://github.com/libspatialindex/libspatialindex/releases/download/1.9.3/spatialindex-src-1.9.3.tar.gz | tar xz
RUN cd spatialindex-src-1.9.3 \
	&& cmake . \
	&& make \
	&& make install \
	&& ldconfig \
	&& make clean
RUN rm -rf spatialindex-src-1.9.3

FROM builder as main


RUN pip install -r requirements.txt
COPY bi_etl_lieux_interets_img bi_etl_lieux_interets_img
COPY tests tests
COPY run.py run.py
ENTRYPOINT [ "python", "run.py" ]
